=== Augmedix/Athelas_Scribe_App_Automation/test/api/resources/json_data/transcript_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Welcome6",
    "definitions": {
        "Welcome6": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "dictation": {
                    "type": "boolean"
                },
                "conversations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Conversation"
                    }
                }
            },
            "required": [
                "conversations",
                "dictation",
                "duration",
                "id"
            ],
            "title": "Welcome6"
        },
        "Conversation": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "speaker": {
                    "type": "string",
                    "format": "integer"
                },
                "words": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/Metadata"
                }
            },
            "required": [
                "id",
                "metadata",
                "speaker",
                "words"
            ],
            "title": "Conversation"
        },
        "Metadata": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "highlight": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "highlight"
            ],
            "title": "Metadata"
        }
    }
}

=== Augmedix/Athelas_Scribe_App_Automation/test/api/resources/json_data/transcript_response_for_7_mnts_audio.json
{
    "id": "provider-3d2239ab-0660-406e-9f27-17e59966c6a1-e7e5f9f6-8edc-4c10-b3b6-1670b80af976-88f7772b-02f5-4671-b048-40287c98458a",
    "duration": "7:10",
    "dictation": false,
    "conversations": [
        {
            "id": 1,
            "speaker": "1",
            "words": "Low back pain, LBP is 1 of the major disabling health conditions, among older adults, age 60 years, or older. Well, most causes of LBP, among older adults, are nonspecific and self limiting. Seniors are prone to develop certain LBP pathology, and or chronic LDP, given their age related physical and psychosocial changes, unfortunately, no review, has previously summarized / discussed various factors that may affect the effect of LBP management, among older adults, accordingly, the objective of the current narrative review, were to comprehensively summarize, common causes, and risk factors, modifiable, and non modifiable developing severe / chronic LVP in older adults, to highlight specific issues, in assessing, and treating seniors, with LBP, and to discuss future research directions. Existing evidence suggests that prevalence rates are severe, and chronic LBP increase with older age, as compared to working age adults,",
            "metadata": {
                "highlight": [
                    "1",
                    "increase",
                    "physical",
                    "60",
                    "Low back pain,",
                    "working",
                    "common"
                ]
            }
        },
        {
            "id": 2,
            "speaker": "3",
            "words": "Yeah.",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 3,
            "speaker": "1",
            "words": "Felt, are more likely to develop certain LBP pathology. Example. Osteoporotic vertebrae fractures, tumors, spinal infection, and lumbar spinal stenosis. Importantly, various age related physical psychological and mental changes, example, spinal degeneration, comorbidities, physical and activity, age related changes in central pain processing, and dementia, as well as multiple risk factors. Example, genetic, gender, and ethnicity, may affect the prognosis and management of LBP in older adults, collectively, by understanding the impacts of various factors on the assessment and treatment of older adults, with LBP. Both clinicians and researchers can work toward the direction of more cost effective and personalized LBP management for older people, keywords, risk factors, spine, disc degeneration, management, low back pain, elderly, genetics, falls, brain Pain assessment, go to background. The average life span of humans has dramatically increased in the last decade due to the advanced in medicine. 1, according to the United nations, the world population of individuals age 60 years or above will triple by 250, 2 in the UK alone, approximately 22% of the population will be 65 years or older by 20, 31, exceeding the number of those age, less than 25 years, 3, however, the fastest growing aging population. Also increases the likelihood of noncommunicable diseases. Example, musculoskeletal skeletal complaints. Studies have suggested that the prevalence of musculoskeletal pain in older adults ranges from 65 to 85 percent for 5, with 36 to 70 percent of them suffering from back pain, 5, 6 low back pain, LBP, is the most common health problem among older adults that It's in pain and disability for 7 to 10. Older or adults, age 65 years, or above. Are the second most common age group to visit physicians, for LBP, 11, earlier research suggests that LBP prevalence progressively increases from teenage 12 to 60 years of age, and then declined, 13 to 16, which may be described to occupational exposure among working 8 adults, 17, 18, or age related changes in pain perception, or still aisism, 19. However, recent studies have revealed that LDP remains ubiquitous among older adults, at their retirement ages, twenty, 21, in population based studies. The 1 year prevalence of LBP, in community, welling seniors, ranged from 13 to 50 percent across the world for thirteen, twenty two to 24, similarly, well, up to 80 percent of older residents in long term care facility experience Dental musculoskeletal pain. Twenty-five to twenty-seven, and 1-third of these cases are LBP, 28. Often older residents pain is under reported, and in an adequately treated, 25 to 27. It is noteworthy that both the incidents and prevalence of severe, and chronic LBP increase with older age, thirteen, twenty nine, 30, docuing it all, seventeen, reported that the one month prevalence of disabling back pain, pain that affected daily activities, within the past month, increased from 3.8 percent a month, people aged between seventy-seven and seventy-nine years, to 9.7 percent among those age, between 90 and 100 years, millions and coworkers, thirty-one. Also found that individuals age 80 years or above, were 3 times more likely to experience severe LBP, than those age, between 50 and 59 years. Because severe LBP, usually results, in poor treatment outcomes, and function",
            "metadata": {
                "highlight": [
                    "27",
                    "one",
                    "20, 31,",
                    "24,",
                    "19",
                    "3.8",
                    "13",
                    "back pain, pain",
                    "9.7",
                    "60",
                    "3,",
                    "90",
                    "28",
                    "back pain, 5, 6 low back pain,",
                    "twenty, 21,",
                    "25",
                    "seventeen,",
                    "65",
                    "16,",
                    "falls,",
                    "thirteen, twenty two",
                    "infection,",
                    "5,",
                    "Pain",
                    "7",
                    "second",
                    "80",
                    "1,",
                    "exposure",
                    "thirteen, twenty nine, 30,",
                    "activity,",
                    "36",
                    "low back pain,",
                    "increase",
                    "250, 2",
                    "12",
                    "fractures,",
                    "physical",
                    "pain",
                    "working 8",
                    "100",
                    "85",
                    "59",
                    "dementia,",
                    "common",
                    "10",
                    "11,",
                    "3",
                    "1",
                    "17, 18,",
                    "multiple",
                    "70",
                    "50"
                ]
            }
        },
        {
            "id": 4,
            "speaker": "3",
            "words": "Yeah.",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 5,
            "speaker": "1",
            "words": "Stability. 17, 32. Timely, LBP management of older adults is crucial. Importantly, compared to working 8 adults. Older adults age 65 years or above, are more likely to develop chronic LBP that less, from more than 3 months, 13, 33. As Spanish study found that the prevalence rates of chronic LBP among females and males age 65 years, or older, were twenty 4.2 and 12.3 percent, respectively, 34, well, in this rarely study documented that the prevalence of chronic LBP in people age 77 years, was as high as 58 percent, 35 dot. Not withstanding the high prevalence of LBP, among older adults. They're pain is usually undertreated, a recent study, showed approximately 25 percent of senior nursing home residents with chronic pain, did not receive analgesics. And only 50% of all anal analgesics were prescribed as standing orders at suboptimal doses, which did not follow geriatric clinical guidelines, 36, 37. According to those guidelines. Older patients with chronic pain should receive analgesics, as a standing dose, rather than on an as needed basis, in order to ensure adequate concentration of analgesic in serum for continuous pain relief, 36, 38. Standing dose analgesics are particularly important for people with cognitive impairment, because they cannot appropriately request medication. Well, under treatment of LBP, in older adults, may be ascribed to the avoidance of high dose analgesics. Example, opioid prescription, it may also be attributed to the difficulty in identifying depressants or causes of LBP. Research has shown that less than 50% of primary care physicians have strong confidence in diagnosing the causes of chronic LVP in older adults, 32 Consequently. This may result in over reliance on medical imaging or in proper LBP management. Example, under treatment, imperatively, untreating or under treating older adults, with LBP may result in sleep disturbances, withdrawal.",
            "metadata": {
                "highlight": [
                    "12.3",
                    "13, 33",
                    "17, 32",
                    "25",
                    "3",
                    "32",
                    "34,",
                    "35",
                    "36, 37",
                    "36, 38. Standing",
                    "58",
                    "65",
                    "77",
                    "as needed",
                    "high",
                    "high dose",
                    "medication",
                    "pain",
                    "pain,",
                    "sleep",
                    "standing",
                    "twenty 4.2",
                    "working 8"
                ]
            }
        }
    ]
}

=== Augmedix/Athelas_Scribe_App_Automation/test/api/resources/json_data/transcript_response.json
{
    "id": "provider-c2ece7eb-bde2-4590-8bc1-07005e3232df-ae11c153-b921-4734-801f-a9764c2b95bf-548df10e-ba69-4b26-b618-03ce7c4b655b",
    "duration": "2:06",
    "dictation": false,
    "conversations": [
        {
            "id": 1,
            "speaker": "2",
            "words": "Hey, how are you doing?",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 2,
            "speaker": "3",
            "words": "I'm okay.",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 3,
            "speaker": "2",
            "words": "Good to hear. I'll catch up with you, just have a seat here. Let's talk about your diabetes. You were taking metformin 500 mg 1 tab twice a day, right?",
            "metadata": {
                "highlight": [
                    "metformin 500 mg 1 tab twice a day,",
                    "diabetes"
                ]
            }
        },
        {
            "id": 4,
            "speaker": "3",
            "words": "Yep.",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 5,
            "speaker": "2",
            "words": "Have you been having any issues?",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 6,
            "speaker": "3",
            "words": "I've been feeling some fatigue, I guess.",
            "metadata": {
                "highlight": [
                    "fatigue,"
                ]
            }
        },
        {
            "id": 7,
            "speaker": "2",
            "words": "And do you check your blood sugar at home?",
            "metadata": {
                "highlight": [
                    "blood sugar"
                ]
            }
        },
        {
            "id": 8,
            "speaker": "3",
            "words": "Every morning. It's usually around 140 or so. Definitely better than what it used to be.",
            "metadata": {
                "highlight": [
                    "140",
                    "morning"
                ]
            }
        },
        {
            "id": 9,
            "speaker": "2",
            "words": "Okay. Let's take a look at your results. Your blood glucose was 143, but your A1c is 6.9. Which is pretty good for your age. We'll continue you on Metformin, since it seems to be working well.",
            "metadata": {
                "highlight": [
                    "6.9",
                    "continue",
                    "A1c",
                    "143,",
                    "blood glucose",
                    "working",
                    "Metformin,"
                ]
            }
        },
        {
            "id": 10,
            "speaker": "1",
            "words": "Sounds good. Not for your hyperlipidemia. Looking at your panel, your LDL, which is the bad 1, is 128, which is trending in the wrong direction compared to last year",
            "metadata": {
                "highlight": [
                    "1,",
                    "LDL,",
                    "128,"
                ]
            }
        },
        {
            "id": 11,
            "speaker": "2",
            "words": "So, are you currently taking pravastatin 10 mg once per day, right?",
            "metadata": {
                "highlight": [
                    "pravastatin 10 mg once per day,"
                ]
            }
        },
        {
            "id": 12,
            "speaker": "1",
            "words": "Yes. How have you been feeling? I experienced some chest pain last month when I was getting out of the car. I didn't think too much of it at the time, because it went away pretty quickly",
            "metadata": {
                "highlight": [
                    "chest pain"
                ]
            }
        },
        {
            "id": 13,
            "speaker": "2",
            "words": "Okay. Well, in that case, I want to get your values back to normal. So, we'll increase your dosage for pravastatin to 20 mg once per day.",
            "metadata": {
                "highlight": [
                    "pravastatin",
                    "increase",
                    "20 mg once per day",
                    "back",
                    "normal"
                ]
            }
        },
        {
            "id": 14,
            "speaker": "1",
            "words": "Okay. Sounds good.",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 15,
            "speaker": "2",
            "words": "Anything else you wanted to ask about?",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 16,
            "speaker": "3",
            "words": "Well, I've been having some back pain after helping my son moved last weekend.",
            "metadata": {
                "highlight": [
                    "back pain"
                ]
            }
        },
        {
            "id": 17,
            "speaker": "2",
            "words": "Have you taken anything for it?",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 18,
            "speaker": "3",
            "words": "I've been taking 800 mg of ibuprofen and then it feels much better.",
            "metadata": {
                "highlight": [
                    "800 mg",
                    "ibuprofen"
                ]
            }
        },
        {
            "id": 19,
            "speaker": "2",
            "words": "That's good. Sometimes that happens after strenuous activity. I want you to monitor it and continue to take ibuprofen as needed. Please call if it doesn't improve in 2 weeks.",
            "metadata": {
                "highlight": [
                    "activity",
                    "2",
                    "ibuprofen as needed",
                    "continue"
                ]
            }
        },
        {
            "id": 20,
            "speaker": "3",
            "words": "Will do.",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 21,
            "speaker": "2",
            "words": "Great. I'll see you next month. I'm going to order a cholesterol screening. Just make sure to take it a week before you come in.",
            "metadata": {
                "highlight": [
                    "cholesterol"
                ]
            }
        },
        {
            "id": 22,
            "speaker": "3",
            "words": "Okay. Will do.",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 23,
            "speaker": "2",
            "words": "All right? Take care.",
            "metadata": {
                "highlight": []
            }
        },
        {
            "id": 24,
            "speaker": "1",
            "words": "Thank you.",
            "metadata": {
                "highlight": []
            }
        }
    ]
}
